# Generated by Django 5.2.5 on 2026-06-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
